spring.application.name=Curricularizacao

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres

# Usuário e senha do PostgreSQL
spring.datasource.username=postgres.btkmrdekidptwritoawk
spring.datasource.password=@GalpaoCultural1

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# API - Gemini
API_KEY_GEMINI_HOMG=AIzaSyBrgt3QkxzO6lNm8xSx6ipFYyNRinRsYBk
API_KEY_GEMINI_PROD=AIzaSyCwwPtFwE_ykducSPwwX9u0_mi_r3y4GQ0